# Generated by Django 4.1.5 on 2023-02-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='debt',
            new_name='credits',
        ),
    ]
