# Generated by Django 4.1.5 on 2023-02-18 01:51

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_rename_debt_client_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
