# Generated by Django 4.1.5 on 2023-02-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0004_alter_client_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
