# Generated by Django 4.1.5 on 2023-02-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0005_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité', models.PositiveIntegerField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('total_credits', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev.produit')),
            ],
        ),
    ]
