# Generated by Django 4.1.5 on 2023-02-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0006_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='quantité',
            new_name='quantite',
        ),
    ]
