# Generated by Django 4.1.5 on 2023-02-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_rename_quantité_credit_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='total_credits',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
