# Generated by Django 4.1.5 on 2023-02-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0009_remove_credit_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dev.produit'),
        ),
    ]
