# Generated by Django 4.1.5 on 2023-02-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0012_remove_credit_client_remove_credit_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='client_produits',
        ),
        migrations.AddField(
            model_name='produit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ClientProduit',
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
