# Generated by Django 4.1.5 on 2023-02-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0014_credit'),
    ]

    operations = [
    ]
