# Generated by Django 4.1.5 on 2023-02-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0016_remove_produit_updated_credit_datecreation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='total_credits',
            new_name='montant',
        ),
    ]
