apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gestioncredit
  namespace: argocd
spec:
  destination:
    namespace: gestioncredit
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/outmanedev/gestioncredit
    path: .
    targetRevision: master
